# Generated by Django 3.2.25 on 2025-03-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_rank', '0004_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
