# Generated by Django 3.2.25 on 2025-03-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_rank', '0005_alter_user_is_superuser'),
    ]

    operations = [
    ]
