# Generated by Django 3.2.25 on 2025-03-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_rank', '0006_auto_20250306_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateMatch',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('resume_id', models.IntegerField()),
                ('job_id', models.IntegerField()),
                ('match_score', models.FloatField()),
            ],
            options={
                'db_table': 'candidate_matches',
            },
        ),
    ]
