# Generated by Django 3.2.25 on 2025-03-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_rank', '0007_candidatematch'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
