# Generated by Django 3.2.25 on 2025-03-08 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume_rank', '0008_auto_20250308_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='job',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='resume_rank.jobdescription'),
            preserve_default=False,
        ),
    ]
