# Generated by Django 3.2.25 on 2025-03-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_rank', '0009_resume_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
            ],
            options={
                'db_table': 'candidates',
            },
        ),
    ]
