# Generated by Django 3.2.25 on 2025-03-12 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume_rank', '0010_candidates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='user',
        ),
        migrations.AddField(
            model_name='resume',
            name='candidate',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='resume_rank.candidates'),
            preserve_default=False,
        ),
    ]
