# Generated by Django 3.2.25 on 2025-03-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_rank', '0011_auto_20250312_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='education_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='experience_years',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
