# Generated by Django 3.2.25 on 2025-03-15 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_rank', '0012_auto_20250315_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdescription',
            old_name='experience_years',
            new_name='experiences_years',
        ),
    ]
