# Generated by Django 3.2.25 on 2025-03-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_rank', '0013_rename_experience_years_jobdescription_experiences_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
