# Generated by Django 3.2.25 on 2025-03-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_rank', '0014_resume_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
