# Generated by Django 3.2.25 on 2025-03-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_rank', '0015_alter_resume_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
