# Generated by Django 5.1.7 on 2025-03-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_rank', '0016_auto_20250315_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='education_level',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='experiences_years',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='required_skills',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
