# Generated by Django 5.1.7 on 2025-05-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_rank', '0017_alter_jobdescription_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
